package ceep.cgl.pyr.sqlite;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class Estructura extends SQLiteOpenHelper {

    // nombre de la base de datos y version actual
    final static String BDD_NAME = "PyR";
    final static int BDD_VERSION = 1;

    // cadena de creacion de tablas
    final static String SQL_CREATE_PREGUNTAS = "CREATE TABLE Preguntas (id INTEGER PRIMARY KEY, texto TEXT NOT NULL, categoria TEXT NOT NULL, idSolucion INTEGER NOT NULL)";
    final static String SQL_CREATE_RESPUESTAS = "CREATE TABLE Respuestas (idPregunta INTEGER NOT NULL , orden INTEGER NOT NULL, texto TEXT NOT NULL, PRIMARY KEY(idPregunta, orden))";
    final static String SQL_CREATE_USUARIOS = "CREATE TABLE Usuarios (idUsuario INTEGER PRIMARY KEY, usuario TEXT NOT NULL, password TEXT NOT NULL)";
    final static String SQL_CREATE_RESULTADOS = "CREATE TABLE Resultados (id INTEGER PRIMARY KEY, idUsuario INTEGER NOT NULL, numaciertos INTEGER NOT NULL, numpreguntas INTEGER NOT NULL, categoria TEXT NOT NULL, tiempo INTEGER NOT NULL)";
    final static String SQL_DROP_PREGUNTAS = "DROP TABLE IF EXISTS Preguntas";
    final static String SQL_DROP_RESPUESTAS = "DROP TABLE IF EXISTS Respuestas";
    final static String SQL_DROP_USUARIOS = "DROP TABLE IF EXISTS Usuarios";
    final static String SQL_DROP_RESULTADOS = "DROP TABLE IF EXISTS Resultados";


    // nombre de las tablas y campos
    final static String TABLA_PREGUNTAS = "Preguntas";
    final static String CAMPO_PREGUNTAS_ID = "id";
    final static String CAMPO_PREGUNTAS_TEXT = "texto";
    final static String CAMPO_PREGUNTAS_CATEGORIA = "categoria";
    final static String CAMPO_PREGUNTAS_SOLUCION = "idSolucion";
    final static String TABLA_RESPUESTAS = "Respuestas";
    final static String CAMPO_RESPUESTAS_ID = "idPregunta";
    final static String CAMPO_RESPUESTAS_ORDEN = "orden";
    final static String CAMPO_RESPUESTAS_TEXT = "texto";
    final static String TABLA_USUARIOS = "Usuarios";
    final static String CAMPO_USUARIOS_ID = "idUsuario";
    final static String CAMPO_USUARIOS_USUARIO = "usuario";
    final static String CAMPO_USUARIOS_PASSWORD = "password";
    final static String TABLA_RESULTADOS = "Resultados";
    final static String CAMPO_RESULTADOS_ID = "id";
    final static String CAMPO_RESULTADOS_USUARIO = "idUsuario";
    final static String CAMPO_RESULTADOS_ACIERTOS = "numaciertos";
    final static String CAMPO_RESULTADOS_PREGUNTAS = "numpreguntas";
    final static String CAMPO_RESULTADOS_CATEGORIA = "categoria";
    final static String CAMPO_RESULTADOS_TIEMPO = "tiempo";

    public Estructura(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version) {
        super(context, BDD_NAME, factory, BDD_VERSION);
    }

    @Override
    public void onCreate(SQLiteDatabase sqLiteDatabase) {
        // CREATE DE LAS TABLAS
        sqLiteDatabase.execSQL(SQL_CREATE_PREGUNTAS);
        sqLiteDatabase.execSQL(SQL_CREATE_RESPUESTAS);
        sqLiteDatabase.execSQL(SQL_CREATE_USUARIOS);
        sqLiteDatabase.execSQL(SQL_CREATE_RESULTADOS);

        cargarDatos(sqLiteDatabase);
    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
        // DROP DE LAS TABLAS
        sqLiteDatabase.execSQL(SQL_DROP_PREGUNTAS);
        sqLiteDatabase.execSQL(SQL_DROP_RESPUESTAS);
        sqLiteDatabase.execSQL(SQL_DROP_USUARIOS);
        sqLiteDatabase.execSQL(SQL_DROP_RESULTADOS);
        // CREATE DE LAS TABLAS
        sqLiteDatabase.execSQL(SQL_CREATE_PREGUNTAS);
        sqLiteDatabase.execSQL(SQL_CREATE_RESPUESTAS);
        sqLiteDatabase.execSQL(SQL_CREATE_USUARIOS);
        sqLiteDatabase.execSQL(SQL_CREATE_RESULTADOS);

        cargarDatos(sqLiteDatabase);
    }

    public void cargarDatos(SQLiteDatabase sqLiteDatabase){

        // cargamos el usuario administrado
        sqLiteDatabase.execSQL("INSERT INTO Usuarios (idUsuario, usuario, password) VALUES (1,'admin','admin1998')");
        // cargamos las preguntas y las respuestas

        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(1,'¿Qué comunidad autonoma limita con 3 provincias: Asturias, Palencia y Bilbao?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(2,'¿Quíen dirigió La Novia Cadáver?','Cine',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(3,'¿Quién marco el gol que hizo campeon a España en el Mundial de Sudafrica 2010?','Deportes',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(4,'¿En que provincia se encuentra el Barranco del Infierno?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(5,'¿Quién dirigió Regreso al futuro?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(6,'¿Cuál es el club español que gano mas Copas del Rey en el siglo XX?','Deportes',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(7,'¿Cuál de los siguientes paises no pertenece a la Liga Arabe?','Geografía',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(8,'¿Con que subtitulo se estreno Terminator 3?','Cine',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(9,'¿Quién era el rival del Real Madrid en un partido de futbol que se inicio en 2004 y termino al año siguiente?','Deportes',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(10,'¿Qué localidad de Alicante lleva las 5 vocales en su nombre?','Geografía',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(11,'¿Cuál de las siguientes peliculas NO es de Arnold Schwarzenegger?','Cine',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(12,'¿En que provincia española nacio Rafael Nadal, el mejor tenista de España?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(13,'¿Qué provincia española tiene una catedral bendecida por el Papa?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(14,'¿Cuál es la primera trilogia que rodo en Hollywood Antonio Banderas?','Cine',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(15,'¿Cuál fue la primera ciudad española a la que se le adjudicaron unos Juegos del Mediterraneo en el siglo XXI?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(16,'¿En que provincia española montarías en Jaca en Jaca?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(17,'¿Cuál de las siguientes series de peliculas NO se considera una trilogia?','Cine',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(18,'¿Cuál de los siguientes pilotos de automovilismo no es de Fórmula 1?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(19,'¿En que provincia española se hacen mas yemas de Santa Teresa?','Geografía',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(20,'¿En que pelicula protagonizada por John Travolta aparecia un bebe que hablaba?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(21,'¿Cuál de los siguientes pilotos de automovilismo no es de Rally?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(22,'¿En que comunidad autonoma se inauguro el primer teleférico de la peninsula Ibérica?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(23,'¿En que pelicula cantaba Stevie Wonder Solo llame para decirte que te quiero?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(24,'¿Cuál de los siguientes pilotos de automovilismo no es de Motociclismo?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(25,'¿En que ciudad encontramos el metro mas largo del mundo?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(26,'El acorazado Potemkin es una pelicula de…','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(27,'¿Cuál de los siguientes apodos no es de Rafa Nadal?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(28,'¿En que provincia andaluza se encuentra Sierra Nevada?','Geografía',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(29,'¿Qué pelicula fantastica, protagonizada por Tobey Maguire, estuvo a la cabeza de los errores cinematograficos en 2004?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(30,'¿A que futbolista se le apodó La Saeta Rubia?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(31,'¿Cómo se llama el meridiano cero?','Geografía',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(32,'¿Quién era el actor de la trilogia de Regreso al Futuro?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(33,'¿En que año se disputo el ultimo Mundial de futbol en el que España fue eliminada por penalties?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(34,'¿Qué pais separa Alaska del resto de Estados Unidos?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(35,'¿Quién dirigio Ivan el Terrible?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(36,'¿Cuál es el equipo de futbol de Pontevedra que ha permanecido mas temporadas en Primera Division?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(37,'¿Cuál de las siguientes ciudades no es de Francia?','Geografía',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(38,'¿Quién era el actor de Grease que tambien aparecio en Pulp Fiction?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(39,'¿Cuál es el equipo español que jugo mas partidos de futbol en Primera sin jugadores extranjeros?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(40,'¿Cuál de las siguientes ciudades no es de España?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(41,'¿Cuál de las siguientes peliculas NO es de John Travolta?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(42,'¿En cuál de los siguientes deportes no se utiliza pelota?','Deportes',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(43,'¿Cuál de las siguientes ciudades no es de Inglaterra?','Geografía',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(44,'¿Quién dirigio Gremlins?','Cine',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(45,'¿A que deporte colocarias a Clayton Kershaw ?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(46,'¿Cuál de las siguientes ciudades no es de Italia?','Geografía',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(47,'¿Quién era el actor de Stuart Little que tambien participo en Mi Pequeño Vampiro?','Cine',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(48,'¿Cómo se llama en golf a una especie de credencial que otorga una ventaja mayor o menor para completar el par del campo?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(49,'¿Cuál de las siguientes ciudades no es de Alemania?','Geografía',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(50,'¿Cómo se lama la produccion española formada por un recopilatorio de 32 cortometrajes en el que se incluye La Pesadilla?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(51,'¿Qué equipo de la NBA jugo Michael Jordan?','Deportes',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(52,'¿En que comunidad autonoma situarias a la provincia de Valladolid?','Geografía',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(53,'¿Qué actor de la pelicula Abre los ojos aparecio tambien en Más allá del jardín?','Cine',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(54,'¿De que color es la pelota de baloncesto?','Deportes',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(55,'¿En que comunidad autonoma bañada por el mar Mediterraneo situarias a Benidorm?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(56,'¿Qué actor de Scooby Doo (Live Action) interpreto a Shaggy Rogers?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(57,'¿Cuál de los siguientes equipos no es de baloncesto NBA?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(58,'¿Qué pais europeo tiene la sede de Carrefour?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(59,'¿Qué actor de Scooby Doo (Live Action) interpreto a Fred Jones?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(60,'¿Cuál es el Grand Slam favorito de Rafael Nadal?','Deportes',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(61,'¿En que comunidad tiene frontera con los Pirineos ?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(62,'¿Qué actor de Scooby Doo (Live Action) interpreto a Daphne Blake?','Cine',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(63,'¿Cuál es el unico club de futbol español que no ha ganado ningun titulo de Copa del Rey de Futbol  hasta ahora?','Deportes',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(64,'¿Qué comunidad autonoma limita con Castilla y Leon Y Castilla La Mancha?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(65,'¿Qué actor de Scooby Doo (Live Action) interpreto a Vilma Dinkley?','Cine',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(66,'¿A que deporte colocarias a Fernando Alonso?','Deportes',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(67,'¿Cuál es la unica provincia que no es de la comunidad autonoma de Aragon?','Geografía',4)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(68,'¿Quién dirigio Los Otros?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(69,'¿En que club de futbol español colocarias a Johan Cruyff?','Deportes',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(70,'¿Con que comunidad autonoma comunica Madrid en la Autovia del Noroeste?','Geografía',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(71,'¿Quién era el actor principal de Esplendor en la hierba que tambien aparecio en Dick Tracy?','Cine',2)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(72,'¿Cuál es el club mas importante de Castilla Y Leon?','Deportes',3)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(73,'¿Qué comunidad autonoma situarias en el Cabo de Finisterre?','Geografía',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(74,'¿Quién era el actor principal de Dulce Pajaro de Juventud que tambien aparecio en El color del dinero?','Cine',1)");
        sqLiteDatabase.execSQL("Insert into Preguntas (id,texto,categoria,Idsolucion) VALUES(75,'¿Cuál es el unico club de futbol español que ha ganado algun titulo de Copa del Rey de Futbol  hasta ahora?','Deportes',1)");



        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(1,1,'Cantabria')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(1,2,'La Rioja')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(1,3,'Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(1,4,'Andalucia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(2,1,'Alfred Hitchcock')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(2,2,'Pedro Almodovar')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(2,3,'Alejandro Amenabar')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(2,4,'Tim Burton')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(3,1,'David Villa')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(3,2,'Andres Iniesta')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(3,3,'Fernando Torres')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(3,4,'Sergio Ramos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(4,1,'Tenerife')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(4,2,'Vizcaya')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(4,3,'Lugo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(4,4,'Asturias')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(5,1,'Orson Welles')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(5,2,'Robert Zemeckis')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(5,3,'Stanley Kubrick')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(5,4,'Quentin Tarantino')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(6,1,'Real Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(6,2,'Sevilla FC')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(6,3,'FC Barcelona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(6,4,'Valencia CF')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(7,1,'Arabia Saudí')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(7,2,'Egipto')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(7,3,'Iran')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(7,4,'Emiratos Arabes Unidos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(8,1,'La maldicion de las verduras')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(8,2,'La maldicion de la perla negra')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(8,3,'La rebelion de las maquinas')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(8,4,'La venganza de los caidos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(9,1,'Athletic Club')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(9,2,'Real Sociedad')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(9,3,'FC Barcelona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(9,4,'RCD Espanyol')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(10,1,'Sax')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(10,2,'San Fulgencio')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(10,3,'Orihuela')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(10,4,'Benidorm')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(11,1,'Un Padre En Apuros')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(11,2,'Terminator')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(11,3,'El sexto día')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(11,4,'Regreso al futuro')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(12,1,'Mallorca')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(12,2,'Lérida')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(12,3,'Zaragoza')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(12,4,'Alicante')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(13,1,'Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(13,2,'Barcelona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(13,3,'Valencia ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(13,4,'Sevilla')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(14,1,'Regreso al futuro')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(14,2,'El señor de los anillos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(14,3,'Spy Kids')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(14,4,'Cocodrilo Dundee')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(15,1,'Almeria')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(15,2,'Castellon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(15,3,'Murcia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(15,4,'Tarragona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(16,1,'Huesca')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(16,2,'Burgos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(16,3,'Oviedo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(16,4,'Pontevedra')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(17,1,'Regreso al futuro')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(17,2,'El señor de los anillos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(17,3,'Harry Potter')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(17,4,'Cariño he encogido a los niños')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(18,1,'Michael Schumacher')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(18,2,'Sebastian Vettel')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(18,3,'Fernando Alonso')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(18,4,'Colin McRae')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(19,1,'Salamanca')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(19,2,'Avila')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(19,3,'Toledo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(19,4,'Badajoz')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(20,1,'Mira quien habla')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(20,2,'Grease')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(20,3,'Phenomenon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(20,4,'Pulp Fiction')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(21,1,'Sébastien Loeb')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(21,2,'Carlos Sainz')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(21,3,'Bjorn Waldegard')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(21,4,'Giacomo Agostini')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(22,1,'Cantabria')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(22,2,'Asturias')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(22,3,'Navarra')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(22,4,'La Rioja')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(23,1,'La Mujer de rojo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(23,2,'Visite nuestro bar')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(23,3,'Dirty Dancing')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(23,4,'Ninguna de las anteriores')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(24,1,'Ángel Nieto')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(24,2,'Valentino Rossi')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(24,3,'Marc Márquez')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(24,4,'Lewis Hamilton ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(25,1,'Londres')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(25,2,'Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(25,3,'Barcelona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(25,4,'New York')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(26,1,'Volker Schlöndorff')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(26,2,'Serguéi M. Eisenstein')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(26,3,'Roman Polanski')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(26,4,'Blake Edwards')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(27,1,'El Gladiador')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(27,2,'El Matador')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(27,3,'El Rey de la Tierra')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(27,4,'El Vikingo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(28,1,'Sevilla')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(28,2,'Cordoba')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(28,3,'Malaga')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(28,4,'Granada')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(29,1,'Spiderman')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(29,2,'Spiderman 2')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(29,3,'Spiderman 3')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(29,4,'Ninguna de las anteriores')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(30,1,'Alfredo Di Stefano')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(30,2,'Emilio Buitragueño')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(30,3,'Cristiano Ronaldo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(30,4,'Karim Benzema')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(31,1,'Trópico de Cancer')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(31,2,'Meridiano Mayor')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(31,3,'Meridiano de Greenwich')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(31,4,'Trópico de Capricornio')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(32,1,'Michael J. Fox')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(32,2,'Brad Pitt')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(32,3,'Johnny Depp')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(32,4,'Helena Bonham Carter')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(33,1,'En el año 2002')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(33,2,'En el año 2006')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(33,3,'En el año 2010')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(33,4,'En el año 2014')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(34,1,'Canadá')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(34,2,'Mexico')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(34,3,'Argentina')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(34,4,'Brasil')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(35,1,'Volker Schlöndorff')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(35,2,'Serguéi M. Eisenstein')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(35,3,'Roman Polanski')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(35,4,'Blake Edwards')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(36,1,'Celta')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(36,2,'Coruxo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(36,3,'Union Sporting Club')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(36,4,'Real Vigo Sporting Club')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(37,1,'Lyon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(37,2,'Dijon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(37,3,'Estrasburgo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(37,4,'Viena')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(38,1,'John Travolta')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(38,2,'Olivia Newton-John')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(38,3,'Stockard Channing')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(38,4,'Jeff Conaway')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(39,1,'Atletico de Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(39,2,'FC Barcelona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(39,3,'Real Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(39,4,'Athletic Club')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(40,1,'Milan')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(40,2,'Toledo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(40,3,'Jaen')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(40,4,'Teruel')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(41,1,'Pulp Fiction')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(41,2,'Kill Bill')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(41,3,'Grease')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(41,4,'Phenomenon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(42,1,'Baloncesto')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(42,2,'Futbol')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(42,3,'Vela')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(42,4,'Tenis')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(43,1,'Londres')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(43,2,'Dortmund')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(43,3,'Manchester')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(43,4,'Liverpool')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(44,1,'Tim Burton')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(44,2,'Chris Columbus')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(44,3,'Joe Dante')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(44,4,'Ivan Reitman')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(45,1,'Futbol sala')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(45,2,'Piragüismo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(45,3,'Rugby')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(45,4,'Beisbol')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(46,1,'Roma')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(46,2,'Venecia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(46,3,'Santa Cruz de Tenerife')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(46,4,'Turin')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(47,1,'Hugh Laurie')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(47,2,'Geena Davis')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(47,3,'Michael J. Fox')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(47,4,'Jonathan Lipnicki')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(48,1,'Handicap')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(48,2,'Match-ball')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(48,3,'Las 2 primeras son correctas')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(48,4,'Ninguna de las 2 primeras son correctas')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(49,1,'Berlin')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(49,2,'Munich')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(49,3,'Frankfurt')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(49,4,'Leicester')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(50,1,'Hay motivo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(50,2,'Papa Piquillo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(50,3,'Las 2 primeras son correctas')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(50,4,'Ninguna de las 2 primeras son correctas')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(51,1,'Chicago Bulls')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(51,2,'Los Angeles Lakers')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(51,3,'San Antonio Spurs')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(51,4,'Boston Celtics')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(52,1,'Castilla La Mancha')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(52,2,'Castilla Y Leon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(52,3,'Extremadura')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(52,4,'Galicia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(53,1,'Najwa Nimri')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(53,2,'Chete Lera')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(53,3,'Eduardo Noriega')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(53,4,'Penelope Cruz')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(54,1,'Rosa')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(54,2,'Naranja')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(54,3,'Verde')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(54,4,'Rojo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(55,1,'Comunidad Valenciana')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(55,2,'Andalucia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(55,3,'Region de Murcia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(55,4,'Cataluña')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(56,1,'Matthew Lillard ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(56,2,'Freddie Prinze, Jr.')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(56,3,'Sarah Michelle Gellar ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(56,4,'Linda Cardellini')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(57,1,'Los Angeles Lakers')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(57,2,'Boston Celtics')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(57,3,'San Antonio Spurs')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(57,4,'Real Madrid Basket')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(58,1,'Francia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(58,2,'Portugal')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(58,3,'Rusia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(58,4,'Paises Bajos')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(59,1,'Matthew Lillard ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(59,2,'Freddie Prinze, Jr.')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(59,3,'Sarah Michelle Gellar ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(59,4,'Linda Cardellini')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(60,1,'Abierto de Australia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(60,2,'Roland Garros')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(60,3,'Wimbledon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(60,4,'Abierto de EE. UU.')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(61,1,'Cataluña')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(61,2,'Comunidad Valenciana')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(61,3,'Region de Murcia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(61,4,'Andalucia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(62,1,'Matthew Lillard ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(62,2,'Freddie Prinze, Jr.')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(62,3,'Sarah Michelle Gellar ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(62,4,'Linda Cardellini')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(63,1,'Deportivo de la Coruña')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(63,2,'Celta')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(63,3,'Real Zaragoza')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(63,4,'Athletic Club')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(64,1,'Comunidad de Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(64,2,'Aragon')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(64,3,'Extremadura')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(64,4,'Galicia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(65,1,'Matthew Lillard ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(65,2,'Freddie Prinze, Jr.')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(65,3,'Sarah Michelle Gellar ')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(65,4,'Linda Cardellini')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(66,1,'Baloncesto')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(66,2,'Futbol')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(66,3,'Tenis')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(66,4,'Automovilismo')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(67,1,'Huesca')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(67,2,'Teruel')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(67,3,'Zaragoza')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(67,4,'Huelva')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(68,1,'Imanol Uribe')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(68,2,'Daniel Monzón')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(68,3,'Pedro Almodovar')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(68,4,'Alejandro Amenabar')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(69,1,'Girona CF')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(69,2,'FC Barcelona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(69,3,'Gimnastic Tarragona')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(69,4,'UE Lleida')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(70,1,'Extremadura')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(70,2,'Cataluña')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(70,3,'Galicia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(70,4,'Comunidad Valenciana')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(71,1,'Natalie Wood')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(71,2,'Warren Beatty')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(71,3,'Pat Hingle')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(71,4,'Barbara Loden')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(72,1,'Unionistas de Salamanca')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(72,2,'Real Avila')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(72,3,'Real Valladolid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(72,4,'Gimnastica Segoviana')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(73,1,'Galicia')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(73,2,'Asturias')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(73,3,'Pais Vasco')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(73,4,'La Rioja')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(74,1,'Paul Newman')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(74,2,'Geraldine Page')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(74,3,'Shirley Knight')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(74,4,'Ed Begley')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(75,1,'Real Madrid')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(75,2,'Celta')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(75,3,'Union Deportiva Las Palmas')");
        sqLiteDatabase.execSQL("Insert into Respuestas (Idpregunta,orden,texto) VALUES(75,4,'Real Oviedo')");




    }
}

